repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests in Docker
        entry: ./scripts/run_tests.sh
        language: script
        types: [python]
    hooks:
      - id: ruff
        name: Run ruff
        entry: ruff check
        language: python
        types: [python]