class Config():
    # Mapping of DeepL language codes to YouTube localization language codes
    deepl_to_youtube_lang_map = {
        "ZH": "zh-CN",   # Chinese Simplified (1,200 million)
        "ES": "es",      # Spanish (460 million)
        "EN-US": "en",   # American English (380 million)
        # "EN-GB": "en",   # British English (380 million)
        "HI": "hi",      # Hindi (340 million)
        "AR": "ar",      # Arabic (310 million)
        "BN": "bn",      # Bengali (230 million)
        "PT-PT": "pt",   # European Portuguese (220 million)
        # "PT-BR": "pt",   # Brazilian Portuguese (220 million)
        "RU": "ru",      # Russian (150 million)
        "JA": "ja",      # Japanese (125 million)
        "DE": "de",      # German (100 million)
        "FR": "fr",      # French (80 million)
        # "UR": "ur",      # Urdu (70 million)
        # "ID": "id",      # Indonesian (45 million)
        # "TH": "th",      # Thai (40 million)
        # "IT": "it",      # Italian (30 million)
        # "FIL": "fil",    # Filipino (30 million)
        # "KO": "ko",      # Korean (30 million)
        # "VI": "vi",      # Vietnamese (25 million)
        # "TR": "tr",      # Turkish (25 million)
        # "FA": "fa",      # Persian (25 million)
        # "NL": "nl",      # Dutch (24 million)
        # "SV": "sv",      # Swedish (10 million)
        # "NO": "no",      # Norwegian (5 million)
        # "DA": "da",      # Danish (5 million)
        # "FI": "fi",      # Finnish (5 million)
        # "EL": "el",      # Greek (5 million)
        # "RO": "ro",      # Romanian (5 million)
        # "SK": "sk",      # Slovak (3 million)
        # "SL": "sl",      # Slovenian (3 million)
        # "HU": "hu",      # Hungarian (3 million)
        # "SR": "sr",      # Serbian (3 million)
        # "LV": "lv",      # Latvian (2 million)
        # "LT": "lt",      # Lithuanian (2 million)
        # "ET": "et",      # Estonian (1 million)
    }
